[package]
name = "ersatz"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
custom_debug_derive = "0.5.1"
once_cell = "1.17.1"
rawsock = "0.3.0"
serde = "1.0.158"
wmi = "0.12.1"
