[package]
name = "ersatz"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
maplit = "1.0.2"
rawsock = "0.3.0"
serde = "1.0.158"
wmi = "0.12.1"
